---
project-machines:
  children:
    masters:
    slaves:
  vars:
    ansible_user: admin

masters:
  hosts:
    master:
      ansible_host: 195.248.242.194

slaves:
  hosts:
    slave:
      ansible_host: 195.248.243.208

manager:
  hosts:
    main:
      ansible_host: 194.5.188.112
      ansible_hostname: main
