---
- hosts: project-machines
  roles:
    - etc-hosts
    - jdk
  tasks:
    - name: Install python and pip
      become: true
      apt:
        deb: "{{ item }}"
        state: present
      loop:
        - http://main:8080/python3_3.5.1-3_amd64.deb
        - http://main:8080/python3-pip_8.1.1-2ubuntu0.4_all.deb
