---
- hosts: project-machines
  roles:
    - etc-hosts
    - iptables
    - jdk
  tasks:
    - name: Install python and pip
      become: true
      apt:
        name: python3-pip
        state: present
        update_cache: true
