---
all:
  vars:
    etc_hosts: "{{ groups['all'] }}"
    etc_hosts_root_dns:
      - 8.8.8.8

    docker_registry_port: 5000
    docker_repository: http://main:8080
    docker_insecure_registries:
      - "{{ groups['docker-registry'] | first }}:{{ docker_registry_port }}"
    docker_sample_image_post_check: m.docker-registry.ir/alpine

    iptables_allowed_hosts: "{{ groups['all'] }}"
    iptables_allowed_ports:
      - 22
      - 3000

    kafka_tweets_topic: tweets
    kafka_hadoop_data_topic: hadoop-data-tweets
    kafka_max_poll_duration: 2000
    kafka_max_poll_records: 10

docker-registry:
  vars:
    docker_registry_container_name: registry
    docker_registry_data_dir: /var/lib/registry
