---
project-machines:
  vars:
    project_config_dir: /etc/election-prediction
    docker_registry: "{{ groups['docker-registry'] | first }}:{{ docker_registry_port }}"
    crawler_server_port: 8001
    stream_processor_server_port: 8002
    collector_server_port: 8004
    collector_group_id: col
    collector_queue_size: 2000
    collector_hdfs_output_dir: /election-prediction/collector
    collector_hdfs_output_file: "{{ collector_hdfs_output_dir }}/out"

crawler:
  vars:
    crawler_request_interval: 10000
    crawler_twitter_debug: false
    crawler_docker_image: "{{ docker_registry }}/election-prediction/crawler"

    crawler_first_candidate_tags: Joe_Biden,JoeBiden,JoeBiden2020,JoeBidenForPresident2020,Biden2020,President_biden
    crawler_second_candidate_tags: Donald_Trump,DonaldTrump,DonaldTrump2020,DonaldTrumpForPresident2020,Trump2020,President_trump

stream-processor:
  vars:
    stream_processor_group_id: sp
    stream_processor_queue_size: 2000
    stream_processor_thread_count: 10
    stream_processor_nlp_url: http://{{ inventory_hostname }}:{{ nlp_port }}/
    stream_processor_image: "{{ docker_registry }}/election-prediction/stream-processor"

    nlp_port: 8003
    nlp_image: "{{ docker_registry }}/election-prediction/emotion-detector"

collector:
  vars:
    collector_tarball_url: "http://main:8080/collector.tar"
    collector_dest: /opt
    collector_path: "{{ collector_dest }}/collector"
