---
project-machines:
  vars:
    project_config_dir: /etc/election-prediction
    docker_registry: "{{ groups['docker-registry'] | first }}:{{ docker_registry_port }}"

crawler:
  vars:
    crawler_request_interval: 10000
    crawler_server_port: 8001
    crawler_twitter_debug: false
    crawler_docker_image: "{{ docker_registry }}/election-prediction/crawler"

    crawler_first_candidate_tags: Joe_Biden,JoeBiden,JoeBiden2020,JoeBidenForPresident2020,Biden2020,President_biden
    crawler_second_candidate_tags: Donald_Trump,DonaldTrump,DonaldTrump2020,DonaldTrumpForPresident2020,Trump2020,President_trump
