---
- name: Copy config file
  become: true
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_path }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify: Restart prometheus
